{% set version = "5.0.0" %}

package:
  name: robotframework-faker
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/r/robotframework-faker/robotframework-faker-{{ version }}.tar.gz
    sha256: 0ba9cc2c353a9a2dd3924869a583f217e6738bff0546a07a3e581186af166531
  - folder: src
    url: https://github.com/guykisel/robotframework-faker/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 0cb18714cb5ae05c658951f794d337c701de5d69d951e2bb04db1f8ec3db1f41

build:
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - faker
    - python >=3.5
    - robotframework
    - wrapt

test:
  source_files:
     - src/tests
  imports:
    - FakerLibrary
  commands:
    - pip check
    - robot src/tests
  requires:
    - pip

about:
  home: https://github.com/guykisel/robotframework-faker
  summary: Robot Framework wrapper for faker, a fake test data generator
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
