# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 6.0.0

package:
  name: robotframework-faker
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/r/robotframework-faker/robotframework_faker-${{ version }}.tar.gz
    sha256: f72c6032d3c347dd235b7c855c66acb8b16392d4ee0267850652c8998899385d
    target_directory: dist
  - url: https://github.com/guykisel/robotframework-faker/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 1f869982e361031c43ded40f5fd775fd1e5ad7ae1363a93d6762c9bf58beef5e
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
  run:
    - faker
    - python >=${{ python_min }}
    - robotframework
    - wrapt

tests:
  - python:
      imports: FakerLibrary
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - robot src/tests

about:
  summary: Robot Framework wrapper for faker, a fake test data generator
  license: MIT
  license_file: dist/LICENSE
  homepage: https://github.com/guykisel/robotframework-faker

extra:
  recipe-maintainers:
    - bollwyvl
